drop table TEMP_DELIVERYREPORT cascade constraints;
-- 代理统计临时表
CREATE GLOBAL TEMPORARY TABLE TEMP_DELIVERYREPORT(
    PARENT_ID               NUMBER(10),
    USER_ID                 NUMBER(10),
    USER_TYPE               CHAR(1),
    RECORD_TYPE             CHAR(1),
    SUBORDINATE             NVARCHAR2(50),
    USER_NAME               NVARCHAR2(50),
    TURNOVER                NUMBER,
    AMOUNT                  NUMBER,
    VALID_AMOUNT            NUMBER,
    MEMBER_AMOUNT           NUMBER,
    MEMBER_BACK_WATER       NUMBER,
    SUBORDINATE_AMOUNT      NUMBER,
    WIN_BACK_WATER          NUMBER,
    REAL_RESULT             NUMBER,
    WIN_BACK_WATER_RESULT   NUMBER,
    PAY_SUPERIOR            NUMBER,
    COMMISSION_BRANCH       NUMBER,
    COMMISSION_GEN_AGENT    NUMBER,
    COMMISSION_STOCKHOLDER  NUMBER,
    COMMISSION_AGENT        NUMBER,
    COMMISSION_MEMBER       NUMBER,
    WIN_COMMISSION_BRANCH   NUMBER,
    WIN_COMMISSION_GEN_AGENT NUMBER,
    WIN_COMMISSION_STOCKHOLDER NUMBER,
    WIN_COMMISSION_AGENT    NUMBER,
    WIN_COMMISSION_MEMBER   NUMBER,
    RATE_CHIEF              NUMBER,
    RATE_BRANCH             NUMBER,
    RATE_GEN_AGENT          NUMBER,
    RATE_STOCKHOLDER        NUMBER,
    RATE_AGENT              NUMBER,
    MONEY_RATE_CHIEF        NUMBER,
    MONEY_RATE_BRANCH       NUMBER,
    MONEY_RATE_GEN_AGENT    NUMBER,
    MONEY_RATE_STOCKHOLDER  NUMBER,
    MONEY_RATE_AGENT        NUMBER,
    SUBORDINATE_CHIEF       NUMBER,
    SUBORDINATE_BRANCH      NUMBER,
    SUBORDINATE_STOCKHOLDER NUMBER,
    SUBORDINATE_GEN_AGENT   NUMBER,
    SUBORDINATE_AGENT       NUMBER,
    RATE                    NUMBER,
    RATE_CHIEF_SET          NUMBER,
    RATE_BRANCH_SET         NUMBER,
    RATE_STOCKHOLDER_SET    NUMBER,
    RATE_GEN_AGENT_SET      NUMBER,
    RATE_AGENT_SET          NUMBER,
    COMMISSION_BRANCH_SET         NUMBER,
    COMMISSION_STOCKHOLDER_SET    NUMBER,
    COMMISSION_GEN_AGENT_SET      NUMBER,
    COMMISSION_AGENT_SET          NUMBER
)ON COMMIT DELETE ROWS;


-- 存储过程返回值
CREATE OR REPLACE PACKAGE statReportResult IS
  type resultRef is ref cursor;

END statReportResult;

/


