CREATE TABLE TB_SHOP_LOTTERY_LOG(
	 ID           NUMBER(10) NOT NULL,
	 SHOP_CODE 		VARCHAR2(50) NOT NULL,
	 PERIOD_NUM 	VARCHAR2(50) NOT NULL,
	 PLAY_TYPE 		VARCHAR2(50) NOT NULL,
	 STATUS 				CHAR(1) DEFAULT 0,
	 CREATE_DATE TIMESTAMP  DEFAULT SYSDATE
);

ALTER TABLE TB_SHOP_LOTTERY_LOG
	ADD CONSTRAINT PK_TB_SHOP_LOTTERY_LOG PRIMARY KEY (ID);
  
  
ALTER TABLE TB_SHOP_LOTTERY_LOG
	ADD CONSTRAINT TB_SHOP_LOTTERY_LOG_UNIQUE UNIQUE(SHOP_CODE,PERIOD_NUM,PLAY_TYPE);
	

CREATE SEQUENCE SEQ_TB_SHOP_LOTTERY_LOG
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;