INSERT
INTO TB_USER_COMMISSION
  (SELECT SEQ_TB_USER_COMMISSION.NEXTVAL,
      USER_ID ,
      USER_TYPE ,
      PLAY_TYPE ,
      PLAY_FINAL_TYPE ,
      COMMISSION_A ,
      COMMISSION_B ,
      COMMISSION_C ,
      BETTING_QUOTAS ,
      ITEM_QUOTAS,
      CREATE_USER ,
      CREATE_TIME ,
      MODIFY_USER ,
      MODIFY_TIME ,
      CHIEF_ID
    FROM
      (SELECT B.USER_ID ,
        B.USER_TYPE ,
        A.PLAY_TYPE ,
        A.PLAY_FINAL_TYPE ,
        A.COMMISSION_A ,
        A.COMMISSION_B ,
        A.COMMISSION_C ,
        A.BETTING_QUOTAS ,
        A.ITEM_QUOTAS,
        A.CREATE_USER ,
        SYSDATE AS CREATE_TIME,
        A.MODIFY_USER ,
        SYSDATE AS MODIFY_TIME,
        B.CHIEF_ID
      FROM TB_USER_COMMISSION_DEFAULT A,
        (SELECT DISTINCT USER_ID , USER_TYPE, CHIEF_ID FROM TB_USER_COMMISSION
        ) B
      WHERE A.PLAY_TYPE=6
      AND A.USER_ID    =B.CHIEF_ID
      ORDER BY A.ID
      )
  );