-------------------------------------------修改可用额度精度----------------------------------------------------------------------------
ALTER TABLE TB_MEMBER_STAFF_EXT ADD  AVAILABLE_CREDIT_LINE_CHAR VARCHAR2(20);
UPDATE TB_MEMBER_STAFF_EXT SET AVAILABLE_CREDIT_LINE_CHAR =TO_CHAR(AVAILABLE_CREDIT_LINE);
UPDATE TB_MEMBER_STAFF_EXT SET AVAILABLE_CREDIT_LINE=NULL;
ALTER TABLE TB_MEMBER_STAFF_EXT MODIFY AVAILABLE_CREDIT_LINE FLOAT(3);
UPDATE TB_MEMBER_STAFF_EXT SET  AVAILABLE_CREDIT_LINE = AVAILABLE_CREDIT_LINE_CHAR;
ALTER TABLE TB_MEMBER_STAFF_EXT MODIFY AVAILABLE_CREDIT_LINE NUMBER(15,3);
ALTER TABLE TB_MEMBER_STAFF_EXT DROP COLUMN AVAILABLE_CREDIT_LINE_CHAR;
-------------------------------------------修改信用额度精度--------------------------------------------------------------
ALTER TABLE TB_MEMBER_STAFF_EXT ADD  TOTAL_CREDIT_LINE_CHAR VARCHAR2(20);
UPDATE TB_MEMBER_STAFF_EXT SET TOTAL_CREDIT_LINE_CHAR =TO_CHAR(TOTAL_CREDIT_LINE);
UPDATE TB_MEMBER_STAFF_EXT SET TOTAL_CREDIT_LINE=NULL;
ALTER TABLE TB_MEMBER_STAFF_EXT MODIFY TOTAL_CREDIT_LINE FLOAT(3);
UPDATE TB_MEMBER_STAFF_EXT SET  TOTAL_CREDIT_LINE = TOTAL_CREDIT_LINE_CHAR;
ALTER TABLE TB_MEMBER_STAFF_EXT MODIFY TOTAL_CREDIT_LINE NUMBER(15,3);
ALTER TABLE TB_MEMBER_STAFF_EXT DROP COLUMN TOTAL_CREDIT_LINE_CHAR;

-- Add/modify columns 
alter table TB_SHOPS_INFO add SEND_MAIL_ACCOUNT NVARCHAR2(200);
alter table TB_SHOPS_INFO add SEND_MAIL_PASSWORD NVARCHAR2(200);
alter table TB_SHOPS_INFO add SEND_MAIL_SMTP NVARCHAR2(200);
alter table TB_SHOPS_INFO add GET_MAIL_ADDRESS1 NVARCHAR2(200);
alter table TB_SHOPS_INFO add GET_MAIL_ADDRESS2 NVARCHAR2(200);
alter table TB_SHOPS_INFO add GET_MAIL_ADDRESS3 NVARCHAR2(200);
alter table TB_SHOPS_INFO add SEND_MAIL_ADDRESS NVARCHAR2(200);

alter table TB_REPLENISH_CHECK modify TYPE_CODE null;
alter table TB_REPLENISH_CHECK modify MONEY null;
alter table TB_REPLENISH_CHECK modify REPLENISH_USER_ID null;
alter table TB_REPLENISH_CHECK modify PERIODS_NUM null;
alter table TB_REPLENISH_CHECK modify BETTING_DATE null;
alter table TB_REPLENISH_CHECK modify WIN_STATE null;
alter table TB_REPLENISH_CHECK modify ODDS null;