DROP TABLE TB_JSSB_PERIODS_INFO;
DROP TABLE TB_JSSB;
DROP TABLE TB_JSSB_HIS;

DROP  SEQUENCE SEQ_TB_JSSB_PERIODS_INFO;
DROP  SEQUENCE SEQ_TB_JSSB;
DROP  SEQUENCE SEQ_TB_JSSB_HIS;

ALTER TABLE  TB_REPLENISH_AUTO_SET_LOG DROP COLUMN  CHANGE_TYPE;
ALTER TABLE  TB_REPLENISH_AUTO_SET_LOG  DROP COLUMN  CHANGE_SUB_TYPE;
ALTER TABLE  TB_REPLENISH_AUTO_SET_LOG  DROP COLUMN  ORGINAL_VALUE;
ALTER TABLE  TB_REPLENISH_AUTO_SET_LOG  DROP COLUMN  NEW_VALUE;
ALTER TABLE TB_REPLENISH_AUTO_SET_LOG DROP COLUMN UPDATE_USERID;
ALTER TABLE TB_REPLENISH_AUTO_SET_LOG DROP COLUMN UPDATE_USERTYPE;