UPDATE TB_PLAY_TYPE SET FINAL_TYPE_NAME= REPLACE(FINAL_TYPE_NAME,'0','') WHERE ODDS_TYPE LIKE 'CQSSC_BALL_%' AND LENGTH(FINAL_TYPE_NAME)=2;

ALTER TABLE TB_FRAME_MEMBER_STAFF  ADD  PASSWORD_UPDATE_DATE DATE  DEFAULT TRUNC(SYSDATE);
ALTER TABLE TB_FRAME_MANAGER_STAFF ADD  PASSWORD_UPDATE_DATE DATE  DEFAULT TRUNC(SYSDATE);

ALTER TABLE TB_FRAME_MEMBER_STAFF  ADD  PASSWORD_RESET_FLAG VARCHAR(1)  DEFAULT 'Y';
ALTER TABLE TB_FRAME_MANAGER_STAFF ADD  PASSWORD_RESET_FLAG VARCHAR(1)  DEFAULT 'Y';

--20130508
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER =6  WHERE PLAY_TYPE='GDKLSF' AND TYPE_CODE LIKE '%LONG';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER =7  WHERE PLAY_TYPE='GDKLSF' AND TYPE_CODE LIKE '%HU';

--20130509
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='2106' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%HU' AND DISPLAY_ORDER='2105';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='3106' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%HU' AND DISPLAY_ORDER='3105';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='4106' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%HU' AND DISPLAY_ORDER='4105';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='5106' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%HU' AND DISPLAY_ORDER='5105';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='6106' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%HU' AND DISPLAY_ORDER='6105';

UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='2105' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%LONG' AND DISPLAY_ORDER='2106';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='3105' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%LONG' AND DISPLAY_ORDER='3106';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='4105' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%LONG' AND DISPLAY_ORDER='4106';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='5105' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%LONG' AND DISPLAY_ORDER='5106';
UPDATE TB_PLAY_TYPE SET DISPLAY_ORDER='6105' WHERE PLAY_TYPE='BJ' AND TYPE_CODE LIKE '%LONG' AND DISPLAY_ORDER='6106';


ALTER TABLE TB_PLAY_TYPE ADD COMMISSION_TYPE_DISPLAY_ORDER NUMBER;

--广东快乐十分大类分类顺序
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1001 WHERE COMMISSION_TYPE='GD_ONE_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1002 WHERE COMMISSION_TYPE='GD_TWO_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1003 WHERE COMMISSION_TYPE='GD_THREE_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1004 WHERE COMMISSION_TYPE='GD_FOUR_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1005 WHERE COMMISSION_TYPE='GD_FIVE_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1006 WHERE COMMISSION_TYPE='GD_SIX_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1007 WHERE COMMISSION_TYPE='GD_SEVEN_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1008 WHERE COMMISSION_TYPE='GD_EIGHT_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1009 WHERE COMMISSION_TYPE='GD_OEDX_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1010 WHERE COMMISSION_TYPE='GD_OEDS_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1011 WHERE COMMISSION_TYPE='GD_OEWSDX_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1012 WHERE COMMISSION_TYPE='GD_HSDS_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1013 WHERE COMMISSION_TYPE='GD_FW_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1014 WHERE COMMISSION_TYPE='GD_ZF_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1015 WHERE COMMISSION_TYPE='GD_ZHDX_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1016 WHERE COMMISSION_TYPE='GD_ZHDS_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1017 WHERE COMMISSION_TYPE='GD_ZHWSDX_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1018 WHERE COMMISSION_TYPE='GD_LH_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1019 WHERE COMMISSION_TYPE='GD_RXH_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1020 WHERE COMMISSION_TYPE='GD_RELZ_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1021 WHERE COMMISSION_TYPE='GD_RXS_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1022 WHERE COMMISSION_TYPE='GD_XTQZ_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1023 WHERE COMMISSION_TYPE='GD_RXF_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=1024 WHERE COMMISSION_TYPE='GD_RXW_BALL';

--重庆时时彩大类分类顺序
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2001 WHERE COMMISSION_TYPE='CQ_ONE_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2002 WHERE COMMISSION_TYPE='CQ_TWO_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2003 WHERE COMMISSION_TYPE='CQ_THREE_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2004 WHERE COMMISSION_TYPE='CQ_FOUR_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2005 WHERE COMMISSION_TYPE='CQ_FIVE_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2006 WHERE COMMISSION_TYPE='CQ_OFDX_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2007 WHERE COMMISSION_TYPE='CQ_OFDS_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2008 WHERE COMMISSION_TYPE='CQ_ZHDX_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2009 WHERE COMMISSION_TYPE='CQ_ZHDS_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2010 WHERE COMMISSION_TYPE='CQ_LH_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2011 WHERE COMMISSION_TYPE='CQ_ZS_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2012 WHERE COMMISSION_TYPE='CQ_QS_BALL';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=2013 WHERE COMMISSION_TYPE='CQ_HS_BALL';

--北京赛车大类分类顺序
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3001 WHERE COMMISSION_TYPE='BJ_BALL_FIRST';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3002 WHERE COMMISSION_TYPE='BJ_BALL_SECOND';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3003 WHERE COMMISSION_TYPE='BJ_BALL_THIRD';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3004 WHERE COMMISSION_TYPE='BJ_BALL_FORTH';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3005 WHERE COMMISSION_TYPE='BJ_BALL_FIFTH';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3006 WHERE COMMISSION_TYPE='BJ_BALL_SIXTH';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3007 WHERE COMMISSION_TYPE='BJ_BALL_SEVENTH';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3008 WHERE COMMISSION_TYPE='BJ_BALL_EIGHTH';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3009 WHERE COMMISSION_TYPE='BJ_BALL_NINTH';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3010 WHERE COMMISSION_TYPE='BJ_BALL_TENTH';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3011 WHERE COMMISSION_TYPE='BJ_1-10_DX';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3012 WHERE COMMISSION_TYPE='BJ_1-10_DS';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3013 WHERE COMMISSION_TYPE='BJ_GROUP';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3015 WHERE COMMISSION_TYPE='BJ_DOUBLSIDE_DX';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3016 WHERE COMMISSION_TYPE='BJ_DOUBLSIDE_DS';
UPDATE TB_PLAY_TYPE SET COMMISSION_TYPE_DISPLAY_ORDER=3014 WHERE COMMISSION_TYPE='BJ_1-5_LH';