--init TB_PLAY_TYPE
SET DEFINE OFF

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_SJ_1', '江苏骰寶', 'K3', 'DXSB', '1', 'K3_SJ', '三军', '1', 'K3_SJ', 'K3_SJ', 1,1);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_SJ_2', '江苏骰寶', 'K3', 'DXSB', '2', 'K3_SJ', '三军', '2', 'K3_SJ', 'K3_SJ', 2,1);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_SJ_3', '江苏骰寶', 'K3', 'DXSB', '3', 'K3_SJ', '三军', '3', 'K3_SJ', 'K3_SJ', 3,1);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_SJ_4', '江苏骰寶', 'K3', 'DXSB', '4', 'K3_SJ', '三军', '4', 'K3_SJ', 'K3_SJ', 4,1);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_SJ_5', '江苏骰寶', 'K3', 'DXSB', '5', 'K3_SJ', '三军', '5', 'K3_SJ', 'K3_SJ', 5,1);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_SJ_6', '江苏骰寶', 'K3', 'DXSB', '6', 'K3_SJ', '三军', '6', 'K3_SJ', 'K3_SJ', 6,1);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_WS_1', '江苏骰寶', 'K3', 'DXSB', '1', 'K3_WS', '围骰', '1', 'K3_WS', 'K3_WS', 7,2);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_WS_2', '江苏骰寶', 'K3', 'DXSB', '2', 'K3_WS', '围骰', '2', 'K3_WS', 'K3_WS', 8,2);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_WS_3', '江苏骰寶', 'K3', 'DXSB', '3', 'K3_WS', '围骰', '3', 'K3_WS', 'K3_WS', 9,2);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_WS_4', '江苏骰寶', 'K3', 'DXSB', '4', 'K3_WS', '围骰', '4', 'K3_WS', 'K3_WS', 10,2);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_WS_5', '江苏骰寶', 'K3', 'DXSB', '5', 'K3_WS', '围骰', '5', 'K3_WS', 'K3_WS', 11,2);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_WS_6', '江苏骰寶', 'K3', 'DXSB', '6', 'K3_WS', '围骰', '6', 'K3_WS', 'K3_WS', 12,2);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_QS', '江苏骰寶', 'K3', 'DXSB', 'QS', 'K3_QS', '全骰', '全骰', 'K3_QS', 'K3_QS', 13,3);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_4', '江苏骰寶', 'K3', 'DXSB', '4', 'K3_DS_4', '点数', '4點', 'K3_DS', 'K3_DS', 14,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_5', '江苏骰寶', 'K3', 'DXSB', '5', 'K3_DS_5', '点数', '5點', 'K3_DS', 'K3_DS', 15,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_6', '江苏骰寶', 'K3', 'DXSB', '6', 'K3_DS_6', '点数', '6點', 'K3_DS', 'K3_DS', 16,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_7', '江苏骰寶', 'K3', 'DXSB', '7', 'K3_DS_7', '点数', '7點', 'K3_DS', 'K3_DS', 17,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_8', '江苏骰寶', 'K3', 'DXSB', '8', 'K3_DS_8', '点数', '8點', 'K3_DS', 'K3_DS', 18,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_9', '江苏骰寶', 'K3', 'DXSB', '9', 'K3_DS_9', '点数', '9點', 'K3_DS', 'K3_DS', 19,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_10', '江苏骰寶', 'K3', 'DXSB', '10', 'K3_DS_9', '点数', '10點', 'K3_DS', 'K3_DS', 20,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_11', '江苏骰寶', 'K3', 'DXSB', '11', 'K3_DS_9', '点数', '11點', 'K3_DS', 'K3_DS', 21,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_12', '江苏骰寶', 'K3', 'DXSB', '12', 'K3_DS_9', '点数', '12點', 'K3_DS', 'K3_DS', 22,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_13', '江苏骰寶', 'K3', 'DXSB', '13', 'K3_DS_8', '点数', '13點', 'K3_DS', 'K3_DS', 23,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_14', '江苏骰寶', 'K3', 'DXSB', '14', 'K3_DS_7', '点数', '14點', 'K3_DS', 'K3_DS', 24,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_15', '江苏骰寶', 'K3', 'DXSB', '15', 'K3_DS_6', '点数', '15點', 'K3_DS', 'K3_DS', 25,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_16', '江苏骰寶', 'K3', 'DXSB', '16', 'K3_DS_5', '点数', '16點', 'K3_DS', 'K3_DS', 26,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DS_17', '江苏骰寶', 'K3', 'DXSB', '17', 'K3_DS_4', '点数', '17點', 'K3_DS', 'K3_DS', 27,4);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_1_2', '江苏骰寶', 'K3', 'DXSB', '1_2', 'K3_CP', '长牌', '12', 'K3_CP', 'K3_CP', 28,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_1_3', '江苏骰寶', 'K3', 'DXSB', '1_3', 'K3_CP', '长牌', '13', 'K3_CP', 'K3_CP', 29,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_1_4', '江苏骰寶', 'K3', 'DXSB', '1_4', 'K3_CP', '长牌', '14', 'K3_CP', 'K3_CP', 30,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_1_5', '江苏骰寶', 'K3', 'DXSB', '1_5', 'K3_CP', '长牌', '15', 'K3_CP', 'K3_CP', 31,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_1_6', '江苏骰寶', 'K3', 'DXSB', '1_6', 'K3_CP', '长牌', '16', 'K3_CP', 'K3_CP', 32,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_2_3', '江苏骰寶', 'K3', 'DXSB', '2_3', 'K3_CP', '长牌', '23', 'K3_CP', 'K3_CP', 33,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_2_4', '江苏骰寶', 'K3', 'DXSB', '2_4', 'K3_CP', '长牌', '24', 'K3_CP', 'K3_CP', 34,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_2_5', '江苏骰寶', 'K3', 'DXSB', '2_5', 'K3_CP', '长牌', '25', 'K3_CP', 'K3_CP', 35,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_2_6', '江苏骰寶', 'K3', 'DXSB', '2_6', 'K3_CP', '长牌', '26', 'K3_CP', 'K3_CP', 36,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_3_4', '江苏骰寶', 'K3', 'DXSB', '3_4', 'K3_CP', '长牌', '34', 'K3_CP', 'K3_CP', 37,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_3_5', '江苏骰寶', 'K3', 'DXSB', '3_5', 'K3_CP', '长牌', '35', 'K3_CP', 'K3_CP', 38,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_3_6', '江苏骰寶', 'K3', 'DXSB', '3_6', 'K3_CP', '长牌', '36', 'K3_CP', 'K3_CP', 39,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_4_5', '江苏骰寶', 'K3', 'DXSB', '4_5', 'K3_CP', '长牌', '45', 'K3_CP', 'K3_CP', 40,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_4_6', '江苏骰寶', 'K3', 'DXSB', '4_6', 'K3_CP', '长牌', '46', 'K3_CP', 'K3_CP', 41,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_CP_5_6', '江苏骰寶', 'K3', 'DXSB', '5_6', 'K3_CP', '长牌', '56', 'K3_CP', 'K3_CP', 42,5);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DP_1_1', '江苏骰寶', 'K3', 'DXSB', '1_1', 'K3_DP', '短牌', '11', 'K3_DP', 'K3_DP', 43,6);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DP_2_2', '江苏骰寶', 'K3', 'DXSB', '2_2', 'K3_DP', '短牌', '22', 'K3_DP', 'K3_DP', 44,6);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DP_3_3', '江苏骰寶', 'K3', 'DXSB', '3_3', 'K3_DP', '短牌', '33', 'K3_DP', 'K3_DP', 45,6);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DP_4_4', '江苏骰寶', 'K3', 'DXSB', '4_4', 'K3_DP', '短牌', '44', 'K3_DP', 'K3_DP', 46,6);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DP_5_5', '江苏骰寶', 'K3', 'DXSB', '5_5', 'K3_DP', '短牌', '55', 'K3_DP', 'K3_DP', 47,6);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DP_6_6', '江苏骰寶', 'K3', 'DXSB', '6_6', 'K3_DP', '短牌', '66', 'K3_DP', 'K3_DP', 48,6);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_DA', '江苏骰寶', 'K3', 'DXSB', 'DA', 'K3_DX', '大小', '大', 'K3_DX', 'K3_DX', 49,7);

INSERT INTO TB_PLAY_TYPE (ID,TYPE_CODE, TYPE_NAME, PLAY_TYPE, PLAY_SUB_TYPE, PLAY_FINAL_TYPE, ODDS_TYPE, SUB_TYPE_NAME, FINAL_TYPE_NAME, COMMISSION_TYPE, AUTO_REPLENISH_TYPE, DISPLAY_ORDER,COMMISSION_TYPE_DISPLAY_ORDER) 
VALUES (SEQ_TB_PLAY_TYPE.NEXTVAL,'K3_X', '江苏骰寶', 'K3', 'DXSB', 'X', 'K3_DX', '大小', '小', 'K3_DX', 'K3_DX', 50,7);

--init TB_PLAY_WIN_INFO
SET DEFINE OFF

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_SJ_1', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_SJ_2', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_SJ_3', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_SJ_4', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_SJ_5', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_SJ_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_WS_1', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_WS_2', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_WS_3', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_WS_4', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_WS_5', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_WS_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_QS', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_4', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_5', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_7', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_8', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_9', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_10', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_11', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_12', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_13', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_14', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_15', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_16', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DS_17', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_1_2', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_1_3', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_1_4', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_1_5', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_1_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_2_3', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_2_4', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_2_5', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_2_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_3_4', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_3_5', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_3_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_4_5', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_4_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_CP_5_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DP_1_1', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DP_2_2', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DP_3_3', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DP_4_4', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DP_5_5', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DP_6_6', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_DA', 'K3', '0', '0', SYSDATE);

INSERT INTO TB_PLAY_WIN_INFO (ID, TYPE_CODE, PLAY_TYPE, PERIODS_NUM, WIN, UPDATE_TIME) 
VALUES (SEQ_TB_PLAY_WIN_INFO.NEXTVAL, 'K3_X', 'K3', '0', '0', SYSDATE);


--update commission
UPDATE TB_USER_COMMISSION_DEFAULT SET PLAY_TYPE=5 WHERE PLAY_FINAL_TYPE LIKE '%K3%';
UPDATE TB_USER_COMMISSION SET PLAY_TYPE=5 WHERE PLAY_FINAL_TYPE LIKE '%K3%';
